channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - loguru=0.6.0
  - wandb=0.12.21
  - pandas=1.4.3
  - flatten-dict=0.4.2
  - matplotlib=3.5.2
  - scikit-learn=1.1.1
  - pydantic=1.9.1
  - plotly=5.9.0
  - tikzplotlib=0.10.1
  - pytorch=1.12.0
  - torchvision=0.13.0
  - pytorch-lightning=1.6.5
