dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argh=0.26.2
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - configparser=5.0.1
  - cryptography=3.2.1
  - cudatoolkit=10.0.130
  - docker-pycreds=0.4.0
  - freetype=2.10.4
  - gitdb=4.0.5
  - gitpython=3.1.11
  - gql=0.1.0
  - graphql-core=3.1.2
  - idna=2.10
  - intel-openmp=2020.2
  - jpeg=9d
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - loguru=0.5.3
  - lz4-c=1.9.2
  - mkl=2020.2
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.19.4
  - nvidia-ml=7.352.0
  - olefile=0.46
  - openssl=1.1.1h
  - pathtools=0.1.2
  - pillow=8.0.1
  - pip=20.3.1
  - promise=2.3
  - protobuf=3.14.0
  - psutil=5.7.3
  - pycparser=2.20
  - pyopenssl=20.0.0
  - pysocks=1.7.1
  - python=3.8.6
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.4.0
  - pyyaml=5.3.1
  - readline=8.0
  - requests=2.25.0
  - sentry-sdk=0.19.4
  - setuptools=49.6.0
  - shortuuid=1.0.1
  - six=1.15.0
  - smmap=3.0.4
  - sqlite=3.34.0
  - tk=8.6.10
  - torchvision=0.2.2
  - urllib3=1.25.11
  - wandb=0.10.12
  - watchdog=0.10.4
  - wheel=0.36.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
