opt:
  epochs: 3
  learning_rate_decay_steps: [1, 2]
  batch_size: 4
env:
  debug: True
  wandb_run_name: "debug-run"
int_dim_est:
  n: 512
imitation:
  n_patches: 512
  n_clusters: 16
  random_patches: True
