opt:
  epochs: 175
  learning_rate_decay_steps: [100, 150]
arch:
  n_channels: 32
  pool_size: 3
  pool_stride: 2
  conv_kernel_size: 3
  use_adaptive_avg_pool: False
  use_relu_after_bottleneck: True
