opt:
  epochs: 80
  batch_size: 128
  learning_rate: 0.003
  learning_rate_decay_gamma: 0.1
  learning_rate_decay_steps: [50, 75]
dmh:
  train_locally_linear_network: True
  patch_size: 6
  n_patches: 2048
  n_clusters: 2048
  k_fraction: 0.4
  use_conv: False
  use_avg_pool: True
  pool_size: 5
  pool_stride: 3
  use_adaptive_avg_pool: True
  adaptive_pool_output_size: 6
  use_batch_norm: True
  use_bottle_neck: True
